version: "3.8"

services:
    node:
        image: node-osirisfc
        container_name: node-osirisfc
        restart: always
        working_dir: /srv
        build:
            args:
                name: ${GIT_USER_NAME}
                email: ${GIT_USER_EMAIL}
                ngversion: 15.2.9
            context: ./dockerfiles/node-18-18
            dockerfile: Dockerfile
        volumes:
            - ./../:/srv
        command: npm run start
        # command: tail -f /dev/null
        networks:
            - default
        ports:
            - 4200:4200
            - 9005:9005
