version: "3.8"

services:
    node:
        image: osirisfc-node
        container_name: osirisfc-node
        restart: always
        working_dir: /srv
        build:
            args:
                ngversion: 15.2.9
            context: ./dockerfiles/node-18-18
            dockerfile: Dockerfile
        volumes:
            - ./../:/srv
        command: npm run start
        # command: tail -f /dev/null
        networks:
            - default
        ports:
            - 4200:4200
    firebase:
        image: osirisfc-firebase
        container_name: osirisfc-firebase
        restart: always
        working_dir: /srv
        build:
            args:
                firebaseversion: 13.0.2
            context: ./dockerfiles/firebase-13-0-2
            dockerfile: Dockerfile
        volumes:
            - ./../:/srv
        command: tail -f /dev/null
        networks:
            - default
        ports:
            - 9005:9005